### PR TITLE
Fixing issue #33 by removing dependency to emarsys log in TransportBu…

### PR DESCRIPTION
**Pull request by laurent35240**
…ilder class

I removed Emarsys log in TransprortBuilder because it caused compilation error if compile code is empty and because it was king of useless in this class.

### CODE REVIEW

**Comment by eghanin** [comment]
Hi
Many thanks for this. 
We will review the changes, and if found suitable, we will merge it in.

Thanks a lot!
Guy

**Comment by eghanin** [comment]
please see : 
https://github.com/emartech/3rd-party-integrations-magento-M2/pull/35

this is our suggested fix for the issue you're experiencing.

Thanks 
Guy

**Comment by laurent35240** [comment]
I added some reviews on this PR but otherwise it fixes our issue.

Laurent

**Comment by eghanin** [comment]
Cheers Laurent.
Your contribution is appreciated !

**Comment by eghanin** [comment]
Than you Laurent, 
We merged our suggested fix to the issue :) and it will be releaaed with our new releaae in a couple of days.

thanks
guy

**Pull request closed without merging**
