### PR TITLE
Fixing exception "Fatal error: Uncaught Error: Call to a member funct…

### PR DESCRIPTION
**Pull request by laurent35240**
…ion getStoreId() on string in /app/vendor/emarsys/emarsys/Model/Template.php:90"

This fix an exception we got when creating a company account on Magento
37460196-cea96c5a-284a-11e8-9f4c-7abc70a09819

### CODE REVIEW

**Comment by eghanin** [comment]
Hi Laurent, 
Thanks for this. 
Could you share with me the Magento version and Plugin version you're working with ?

Thanks very much .. 
Guy

**Comment by laurent35240** [comment]
Hi,

We are working with Magento Enterprise 2.2.3 and we use version from master of your github repository (currently version 1.0.9)

Regards,
Laurent

**Comment by eghanin** [comment]
Thank you laurent. 

Guy

**Comment by laurent35240** [comment]
Hi

Why did you close this PR without merging it?
Did you find another solution for this issue?

Laurent

**Comment by eghanin** [comment]
Hi Laurent, 
We actually did take your changes and merged them with other changes we did. 
Our Dev team told me it was added to another PR , but I am not sure exactly which one ( we had 36 commits  in the passed 2 weeks .
In any case, you're changes are always taken seriously!

Thanks very much !
Guy

**Pull request closed without merging**
